vich_uploader:
  db_driver: orm

  mappings:
    avatar:
      uri_prefix: uploads/images/avatar
      upload_destination: "%kernel.project_dir%/public/images/avatar"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    products_left:
      uri_prefix: /uploads/images/product_left
      upload_destination: "%kernel.project_dir%/public/uploads/images/product_left"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    products_right:
      uri_prefix: /uploads/images/product_right/
      upload_destination: "%kernel.project_dir%/public/uploads/images/product_right"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
